name: CI devops 2023
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: #TODO 
  pull_request:

jobs:
        build:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
      
            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                java-version: '11'
                distribution: 'adopt'
      
            - name: Change to project directory
              run: cd simple-api
      
            - name: Build with Maven
              run: mvn clean install
      

                
                  
          