name: Test Backend
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "temurin"
      - name: Build with Maven
        working-directory: ./simple-api
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=tahirhiba_devops-livecoding -Dsonar.organization=tahirhiba -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{secrets.SONAR_TOKEN }}  --file ./pom.xml
  